global:
    # 全局路径 留空则为根目录.
    prefix : 
module:
    qq:
        # qqinfo路径 最后结果为 全局路径 + 该路径
        prefix : "/qqinfo"
    yiyan:
        # yiyan路径 最后结果为 全局路径 + 该路径
        prefix : "/yiyan"
    ip:
        # 留空或False将不开启此功能
        enable : False
        # ip路径 最后结果为 全局路径 + 该路径
        prefix : "/ip"
    randomimg:
        prefix : "/randomimg"